src/objects/ChampionshipPoints__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>PointsAwarded__c</fullName>
        <label>Points Awarded</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Championship Points</label>
</CustomObject>

src/objects/Contestant__c.object
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContestantService.cls
public class ContestantService 
{
	public static void awardChampionshipPoints(Set<Id> contestantIds)
	{
		ApplicationUnitOfWork uow = new ApplicationUnitOfWork();

		// Apply championship points to selected contestants		
		awardChampionshipPoints(uow, new ContestantsSelector().selectById(contestantIds));

		uow.commitWork();
	}

	public static void awardChampionshipPoints(fflib_SObjectUnitOfWork uow, List<Contestant__c> contestants)
	{
		// Apply championship points to given contestants		
		for(Contestant__c contestant : contestants)
		{
			// Determine points to award for the given position
			ChampionshipPoints__c pointsForPosition = 
				ChampionshipPoints__c.getInstance(String.valueOf(contestant.RacePosition__c));
			if(pointsForPosition!=null)
			{
				// Apply points and register for udpate with uow
				contestant.ChampionshipPoints__c = pointsForPosition.PointsAwarded__c;
				uow.registerDirty(contestant);
			}
		}		
	}

	public static void retireFromRace(List<RaceRetirement> retirements)
	{
		throw new ContestantServiceException('Not implemented');
	}

	public class ContestantServiceException extends Exception {} 

	public class RaceRetirement
	{
		public Id contestantId;
		public String reason;
	}	
}