src/objects/Contestant__c.object
<CustomObject>
    <fields>
        <fullName>Driver__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Driver</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
            <filterItems>
                <field>Driver__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only Drivers who&apos;s status is active are permitted.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Driver__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <referenceTo>Race__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Driver__c.object
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Race__c.object
<CustomObject>
    <fields>
        <fullName>Season__c</fullName>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Races</relationshipLabel>
        <relationshipName>Races</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Season__c.object
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Application.cls
public class Application 
{
	// Configure and create the UnitOfWorkFactory for this Application
	public static final UnitOfWorkFactory UnitOfWork = 
		new UnitOfWorkFactory(
				new List<SObjectType> { 
					Driver__c.SObjectType, 
					Season__c.SObjectType, 
				  	Race__c.SObjectType, 
				  	Contestant__c.SObjectType });	

	// Configure and create the DomainFactory for this Application
	public static final DomainFactory Domain = 
		new DomainFactory(
			// Map SObjectType to Domain Class Constructors 
			new Map<SObjectType, Type> {
					Team__c.SObjectType => Teams.Constructor.class,
					Race__c.SObjectType => Races.Constructor.class,
					Car__c.SObjectType => Cars.Constructor.class,
					Driver__c.SObjectType => Drivers.Constructor.class,
					Contestant__c.SObjectType => Contestants.Constructor.class }, 
			// Map SObjectType to Selector Class
			new Map<SObjectType, Type> {
					Team__c.SObjectType => TeamsSelector.class,
					Race__c.SObjectType => RacesSelector.class,
					Car__c.SObjectType => CarsSelector.class,
					Driver__c.SObjectType => DriversSelector.class,
					Contestant__c.SObjectType => ContestantsSelector.class });

	/**
	 * Class implements a Unit of Work factory
	 **/
	public class UnitOfWorkFactory
	{
		private List<SObjectType> objectTypes;

		private UnitOfWorkFactory(List<SObjectType> objectTypes)
		{
			this.objectTypes = objectTypes;
		}

		public fflib_SObjectUnitOfWork newInstance()
		{
			return new fflib_SObjectUnitOfWork(objectTypes);
		}
	}

	/**
	 * Class implements a Domain class factory
	 **/
	public class DomainFactory 
	{
		private Map<SObjectType, Type> sObjectByDomainConstructorType;
		private Map<SObjectType, Type> sObjectBySelectorType;

		public DomainFactory(
			Map<SObjectType, Type> sObjectByDomainConstructorType,
			Map<SObjectType, Type> sObjectBySelectorType)
		{
			this.sObjectByDomainConstructorType = sObjectByDomainConstructorType;
			this.sObjectBySelectorType = sObjectBySelectorType;
		}			

		/**
		 * Dynamically constructs an instance of a Domain class for the given record Ids
		 **/
		public fflib_SObjectDomain newInstance(Set<Id> recordIds)
		{
			// No point creating an empty Domain class
			if(recordIds.size()==0)
				return null;

			// Determine SObjectType and Apex classes for Domain and Selector classes
			SObjectType domainSObjectType = new List<Id>(recordIds)[0].getSObjectType();
			Type domainConstructorClass = sObjectByDomainConstructorType.get(domainSObjectType);
			if(domainConstructorClass==null)
				throw new ApplicationException('Selector class not found for SObjectType ' + domainSObjectType);
			Type selectorClass = sObjectBySelectorType.get(domainSObjectType);
			if(domainConstructorClass==null)
				throw new ApplicationException('Domain constructor class not found for SObjectType ' + domainSObjectType);

			// Construct Selector class and query by Id for the records
			fflib_SObjectSelector selector =
				(fflib_SObjectSelector) selectorClass.newInstance();
			List<SObject> records = selector.selectSObjectsById(recordIds);

			// Construct Domain class passing in the queried records
			fflib_SObjectDomain.IConstructable domainConstructor = 
				(fflib_SObjectDomain.IConstructable) domainConstructorClass.newInstance();		
			return domainConstructor.construct(records);
		}		
	}

	public class ApplicationException extends Exception { }
}