src/objects/Contestant__c.object
<CustomObject>
    <fields>
        <fullName>Driver__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Driver</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
            <filterItems>
                <field>Driver__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only Drivers who&apos;s status is active are permitted.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Driver__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <referenceTo>Race__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Driver__c.object
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Race__c.object
<CustomObject>
    <fields>
        <fullName>Season__c</fullName>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Races</relationshipLabel>
        <relationshipName>Races</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Season__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
        <label>Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestData.cls
public class TestData 
{
	/** 
	 * Returns a JSON string for a test / sample import
	 **/
	public static String asJSON()
	{
		return 
			'{' +
				'"drivers" : [ ' +
					'{' +
						'"name" : "Lewis Hamilton",' + 
						'"nationality" : "British",' + 
						'"driverId" : "44",' + 
						'"twitterHandle" : "lewistwitter"' +
					'}' +
				'],' +
				'"seasons" : [ ' +
					'{' +
						'"year" : "2013",' +
						'"races" : [' +
							'{' +
								'"round" : 1,' +
								'"name" : "Spain",' +
								'"contestants" : [' +
									'{' +
										'"driverId" : "44",' +
										'"championshipPoints" : 44,' +
										'"dnf" : false,' +
										'"qualification1LapTime" : 123,' + 
										'"qualification2LapTime" : 124,' + 
										'"qualification3LapTime" : 125' + 
									'}' +
								']' +
							'}' +
						']' + 
					'}' +
				']' +
			'}';
	}

	public static void createVolumeDataForViewStateTest()
	{
		// Create a big race!
		List<Driver__c> drivers = new List<Driver__c>();
		for(Integer driverIdx = 0; driverIdx < 50; driverIdx++)
			drivers.add(
				new Driver__c(
					Name = 'Driver #' + driverIdx, 
					DriverId__c = '#' + driverIdx,
					TwitterHandle__c = 'twitter' + driverIdx));

		// Create records
		fflib_SObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		Season__c season = new Season__c(Name = 'Volume Test', Year__c = '2015');
		Race__c race = new Race__c(Name = 'Volume Race');
		uow.registerNew(season);
		uow.registerNew(race, Race__c.Season__c, season);
		for(Driver__c driver : drivers)
		{
			uow.registerNew(driver);
			Contestant__c contestant = new Contestant__c();
			uow.registerNew(contestant, Contestant__c.Race__c, race);
			uow.registerRelationship(contestant, Contestant__c.Driver__c, driver);
		}
		uow.commitWork();
	}
}